algoritmo "EXERCICIO_10"
var
       B, C, H, AREA : REAL
inicio

      // ENTRADA DE DADOS
        ESCREVA ("QUAL O VALOR DE B: ")
        LEIA (B)
        ESCREVA ("QUAL O VALOR DE b: ")
        LEIA (C)
        ESCREVA ("QUAL O VALOR DE H: ")
        LEIA (H)
        
      // PROCESSAMENTO
      
      AREA <- (B + C) / 2 * H
      
      // SAIDA DE DADOS
      
      ESCREVAL ("AREA = ", AREA:8:2)

fimalgoritmo