Algoritmo "EXERCICIO_6"

Var
// Seção de Declarações das variáveis
   N1 , N2,  DIVISAO : REAL


Inicio

      //DADOS DE ENTRADA
      escreva ("digite um numero : ")
      leia (n1)
      
      escreva ("digite um numero : ")
      leia (n2)
      
      //precessamento
      
      divisao <- n1 / n2
      
      // saida de dados
      escreval ("divisao = " , divisao )

Fimalgoritmo